// core/loader/interface.ts — swap-ready loader abstraction.
//
// Authority: ARCHITECTURE.md §2 module map; LOADER-CONTRACT.md §8
// (dependency ordering Organizer → Venue → Event; per-object mechanism).
//
// Two implementations planned:
//   - DryRunLoader (Phase 2): emits JSON of what WOULD be written;
//     no BE calls, no Mongo writes
//   - MongoDirectLoader (Phase 3): venue POST → AutoMaster + organizer POST
//     + event direct-Mongo insertOne per LOADER-CONTRACT §8.2; AIDI
//     greenlight required before construction
//
// The Phase 1 PLAN includes a third future impl (mongo-bulk-enrich) when
// CALBEAF-110 unparks; that's a one-file swap behind this interface.

import type { ObjectId } from "mongodb";

// ─────────────────────────────────────────────────────────────────────────
// Document shapes — the actual fields we'd write per LOADER-CONTRACT
// ─────────────────────────────────────────────────────────────────────────

/**
 * Organizer document per LOADER-CONTRACT §4. shortName is generated by
 * loader per §4.2 charset rules. lookup-before-create per §4.3.
 */
export interface OrganizerDoc {
  fullName: string;
  shortName: string;
  appId: string;  // Mongo convention: string "1" not number 1 (Porter+FE; 2026-05-01)
  fb_profile_url?: string;
  discovery_type?: string;
  event_count?: number;
  isDiscovered: true;
  discoverySource: string;
  /** GUARDRAILS H11: per-cycle UUID; rollback = deleteMany({discoveryBatchId}). */
  discoveryBatchId: string;
}

/**
 * Venue document per LOADER-CONTRACT §3. Loader supplies §3.1 hard
 * minimums (name, lat, lng) + §3.2 strongly-recommended. BE AutoMaster
 * computes mastered chain at POST time (§3.3); loader leaves null
 * for FE-wins policy.
 */
export interface VenueDoc {
  name: string;
  latitude: number;
  longitude: number;
  address?: string;
  city?: string;
  state?: string;
  country?: string;
  appId: string;  // Mongo convention: string "1" not number 1 (Porter+FE; 2026-05-01)
  isDiscovered: true;
  discoverySource: string;
  /** GUARDRAILS H11: per-cycle UUID; rollback = deleteMany({discoveryBatchId}). */
  discoveryBatchId: string;
}

/**
 * Event document per LOADER-CONTRACT §5 + §6. Loader pre-computes the
 * full denorm bundle (§6.1 + §6.2 + §6.3 + §6.4) so direct Mongo
 * insertOne can land without BE enrichment.
 */
export interface EventDoc {
  // §5.1 hard minimums
  appId: string;  // Mongo convention: string "1" not number 1 (Porter+FE; 2026-05-01)
  title: string;
  // Date objects (not strings) so Mongo $gte/$lt dedup range queries
  // match. BSON serializes as ISO 8601 UTC. Was string-typed; broke dedup
  // (2026-04-30 first --live: 901 dup groups). Fixed in denorm.toUtcDate.
  startDate: Date;
  endDate: Date;
  // §5.2 niche-harvest minimums
  categoryFirst: string;
  categoryFirstId: ObjectId | null; // resolved at insert time via category cache
  categorySecond?: string | null;
  categorySecondId?: ObjectId | null;
  categoryThird?: string | null;
  categoryThirdId?: ObjectId | null;
  // §6.1 venue denorm
  venueID: ObjectId | null;          // populated after venue POST
  venueTimezone: string | null;
  venueCityName: string | null;
  venueGeolocation: { type: "Point"; coordinates: [number, number] } | null;
  // §6.1 mastered chain (from venue POST response)
  masteredCityId: string | null;
  masteredCityName: string | null;
  masteredCityGeolocation: { type: "Point"; coordinates: [number, number] } | null;
  masteredDivisionId: string | null;
  masteredDivisionName: string | null;
  masteredRegionId: string | null;
  masteredRegionName: string | null;
  masteredCountryId: string | null;
  masteredCountryName: string | null;
  // §6.2 loader-derived
  ownerOrganizerID: ObjectId | null;
  authorOrganizerID: ObjectId | null;
  enrichmentStatus: "complete";
  trustLevel: string;
  isDiscovered: true;
  discoverySource: string;
  /** GUARDRAILS H11: per-cycle UUID; rollback = deleteMany({discoveryBatchId}). */
  discoveryBatchId: string;
  shortTitle?: string;
  description?: string;
  // §6.3 classifier-derived + override
  travelWorthy: boolean | null;
  travelWorthyOverride: boolean | null;
  beginnerFriendly: boolean | null;
  beginnerFriendlyOverride: boolean | null;
  forBeginners: boolean | null;
  forBeginnersOverride: boolean | null;
  // §10 RRULE
  isRepeating: boolean;
  recurrenceRule: string | null;
}

// ─────────────────────────────────────────────────────────────────────────
// Loader interface
// ─────────────────────────────────────────────────────────────────────────

export interface LoadCounts {
  organizers_attempted: number;
  organizers_created: number;
  organizers_existing: number;
  venues_attempted: number;
  venues_created: number;
  venues_existing: number;
  events_attempted: number;
  events_inserted: number;
  events_skipped_existing: number;
  events_failed: number;
}

export interface LoadOpts {
  dryRun: boolean;
  /** Cap on events processed in a single run (safety for first live runs). */
  maxEvents?: number;
}

export interface Loader {
  readonly name: string;

  /**
   * Lookup-or-create an organizer per LOADER-CONTRACT §4.
   * Returns the resolved Mongo _id (real for live; sentinel for dry-run).
   */
  upsertOrganizer(doc: OrganizerDoc): Promise<ObjectId | string>;

  /**
   * POST a venue (or 409 → existing) per LOADER-CONTRACT §3 + §8.3.
   * Returns the resolved Mongo _id AND the BE response with mastered
   * chain so the caller can pre-compute event denorm.
   */
  upsertVenue(doc: VenueDoc): Promise<{
    venueId: ObjectId | string;
    masteredChain: VenueMasteredChainResponse;
  }>;

  /**
   * Insert a fully-formed event document (§6 denorm bundle pre-computed).
   * 409 path catches duplicate by (title-normalized, local-start-date,
   * venue-tz) per §8.3.
   */
  insertEvent(doc: EventDoc): Promise<{
    eventId: ObjectId | string;
    status: "inserted" | "skipped_existing" | "failed";
    detail?: string;
  }>;

  /** Final counts; dry-run includes tallies even though nothing wrote. */
  counts(): LoadCounts;
}

/**
 * Subset of the BE venue POST response carrying just the mastered chain
 * + timezone needed for event denorm.
 */
export interface VenueMasteredChainResponse {
  timezone: string | null;
  geolocation: { type: "Point"; coordinates: [number, number] } | null;
  masteredCityId: string | null;
  masteredCityName: string | null;
  masteredDivisionId: string | null;
  masteredDivisionName: string | null;
  masteredRegionId: string | null;
  masteredRegionName: string | null;
  masteredCountryId: string | null;
  masteredCountryName: string | null;
}
